// These types were generated by the Supabase MCP server for the CriteriaGuard project.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      audit_log: {
        Row: {
          action_type: string
          actor: string
          entry_hash: string
          id: string
          metadata: Json | null
          previous_hash: string
          result: string | null
          sequence: number
          target_id: string | null
          target_type: string | null
          timestamp: string
        }
        Insert: {
          action_type: string
          actor: string
          entry_hash: string
          id?: string
          metadata?: Json | null
          previous_hash: string
          result?: string | null
          sequence?: number
          target_id?: string | null
          target_type?: string | null
          timestamp?: string
        }
        Update: {
          action_type?: string
          actor?: string
          entry_hash?: string
          id?: string
          metadata?: Json | null
          previous_hash?: string
          result?: string | null
          sequence?: number
          target_id?: string | null
          target_type?: string | null
          timestamp?: string
        }
        Relationships: []
      }
      bidders: {
        Row: {
          current_step: string | null
          id: string
          name: string
          processed_count: number | null
          status: string
          tender_id: string | null
          total_count: number | null
        }
        Insert: {
          current_step?: string | null
          id?: string
          name: string
          processed_count?: number | null
          status?: string
          tender_id?: string | null
          total_count?: number | null
        }
        Update: {
          current_step?: string | null
          id?: string
          name?: string
          processed_count?: number | null
          status?: string
          tender_id?: string | null
          total_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "bidders_tender_id_fkey"
            columns: ["tender_id"]
            isOneToOne: false
            referencedRelation: "tenders"
            referencedColumns: ["id"]
          }
        ]
      }
      criteria: {
        Row: {
          approved_at: string | null
          approved_by: string | null
          category: string
          criterion_code: string
          evidence_documents: string[] | null
          id: string
          mandatory: boolean
          mandatory_confidence: string
          source_clause: string | null
          tender_id: string | null
          text: string
          threshold_comparison: string | null
          threshold_period: string | null
          threshold_unit: string | null
          threshold_value: number | null
          source_page: number | null
        }
        Insert: {
          approved_at?: string | null
          approved_by?: string | null
          category: string
          criterion_code: string
          evidence_documents?: string[] | null
          id?: string
          mandatory: boolean
          mandatory_confidence?: string
          source_clause?: string | null
          tender_id?: string | null
          text: string
          threshold_comparison?: string | null
          threshold_period?: string | null
          threshold_unit?: string | null
          threshold_value?: number | null
        }
        Update: {
          approved_at?: string | null
          approved_by?: string | null
          category?: string
          criterion_code?: string
          evidence_documents?: string[] | null
          id?: string
          mandatory?: boolean
          mandatory_confidence?: string
          source_clause?: string | null
          tender_id?: string | null
          text?: string
          threshold_comparison?: string | null
          threshold_period?: string | null
          threshold_unit?: string | null
          threshold_value?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "criteria_tender_id_fkey"
            columns: ["tender_id"]
            isOneToOne: false
            referencedRelation: "tenders"
            referencedColumns: ["id"]
          }
        ]
      }
      extractions: {
        Row: {
          bidder_id: string | null
          created_at: string | null
          criterion_id: string | null
          extracted_value: string | null
          extracted_value_numeric: number | null
          extraction_confidence: number | null
          id: string
          not_found_reason: string | null
          ocr_quality: string | null
          source_document: string | null
          source_excerpt: string | null
          source_page: number | null
          value_found: boolean
        }
        Insert: {
          bidder_id?: string | null
          created_at?: string | null
          criterion_id?: string | null
          extracted_value?: string | null
          extracted_value_numeric?: number | null
          extraction_confidence?: number | null
          id?: string
          not_found_reason?: string | null
          ocr_quality?: string | null
          source_document?: string | null
          source_excerpt?: string | null
          source_page?: number | null
          value_found: boolean
        }
        Update: {
          bidder_id?: string | null
          created_at?: string | null
          criterion_id?: string | null
          extracted_value?: string | null
          extracted_value_numeric?: number | null
          extraction_confidence?: number | null
          id?: string
          not_found_reason?: string | null
          ocr_quality?: string | null
          source_document?: string | null
          source_excerpt?: string | null
          source_page?: number | null
          value_found?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "extractions_bidder_id_fkey"
            columns: ["bidder_id"]
            isOneToOne: false
            referencedRelation: "bidders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "extractions_criterion_id_fkey"
            columns: ["criterion_id"]
            isOneToOne: false
            referencedRelation: "criteria"
            referencedColumns: ["id"]
          }
        ]
      }
      tenders: {
        Row: {
          created_at: string | null
          file_path: string
          id: string
          locked_at: string | null
          locked_by: string | null
          status: string
          title: string
        }
        Insert: {
          created_at?: string | null
          file_path: string
          id?: string
          locked_at?: string | null
          locked_by?: string | null
          status?: string
          title: string
        }
        Update: {
          created_at?: string | null
          file_path?: string
          id?: string
          locked_at?: string | null
          locked_by?: string | null
          status?: string
          title?: string
          created_by?: string | null
        }
        Relationships: []
      }
      verdicts: {
        Row: {
          bidder_id: string | null
          computed_at: string | null
          criterion_id: string | null
          extraction_id: string | null
          id: string
          overridden_at: string | null
          overridden_by: string | null
          override_action: string | null
          override_reason: string | null
          reason: string
          review_sub_reason: string | null
          status: string
        }
        Insert: {
          bidder_id?: string | null
          computed_at?: string | null
          criterion_id?: string | null
          extraction_id?: string | null
          id?: string
          overridden_at?: string | null
          overridden_by?: string | null
          override_action?: string | null
          override_reason?: string | null
          reason: string
          review_sub_reason?: string | null
          status: string
        }
        Update: {
          bidder_id?: string | null
          computed_at?: string | null
          criterion_id?: string | null
          extraction_id?: string | null
          id?: string
          overridden_at?: string | null
          overridden_by?: string | null
          override_action?: string | null
          override_reason?: string | null
          reason?: string
          review_sub_reason?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "verdicts_bidder_id_fkey"
            columns: ["bidder_id"]
            isOneToOne: false
            referencedRelation: "bidders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "verdicts_criterion_id_fkey"
            columns: ["criterion_id"]
            isOneToOne: false
            referencedRelation: "criteria"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "verdicts_extraction_id_fkey"
            columns: ["extraction_id"]
            isOneToOne: false
            referencedRelation: "extractions"
            referencedColumns: ["id"]
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
